"""add embedding to chunks

Revision ID: e0b52fd47e79
Revises: 439b654186b2
Create Date: 2026-03-09 10:12:52.025159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

#MANUAL:
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'e0b52fd47e79'
down_revision: Union[str, Sequence[str], None] = '439b654186b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    #MANUAL:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    #AUTO: 
    op.add_column('chunks', sa.Column('embedding', Vector(384), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'embedding')
    # ### end Alembic commands ###
