"""add api_key_hash to organizations

Revision ID: eaad2f43ced3
Revises: e0b52fd47e79
Create Date: 2026-03-10 18:26:14.176240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaad2f43ced3'
down_revision: Union[str, Sequence[str], None] = 'e0b52fd47e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('api_key_hash', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'organizations', ['api_key_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'api_key_hash')
    # ### end Alembic commands ###
